### PR TITLE
Changes to Logo / title / subtitle #7

### PR DESCRIPTION
**Pull request by Okhayeeli**
## Description
I changed the  Logo / title / subtitle in issue #7 for Batch 6
photo_6275991944937193797_x

## Additional Information

- [x] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [x] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

## Related Issues

_Closes #{7}_

Your ENS/address:0x84fF709680E9378734Bae1D3B55C6568d21671c3

### CODE REVIEW

**Comment by derrekcoleman** [comment]
Looks great! I'll leave this open for a few more days in case anyone would like to give feedback, then we can merge 🤝

**Comment by MayowaObisesan** [comment]
I think this looks really good.

I only have one suggestion though. Can the scaffold-eth logo be added before the #6 in the image you shared. That way the #6 shows it's for scaffold-eth without having to describe it to anyone.

**Comment by Okhayeeli** [comment]
@derrekcolteman, thank you so much
@MayowaObisesan you mean like overlay this on the previous image?.
@kocaemre thank you for your review

**Comment by MayowaObisesan** [comment]
Not overlay the image per se. I'm just suggesting that the scaffold-eth image is beside the #6 from the screenshot being shared.
I hope this is clearer.

**Comment by Okhayeeli** [comment]
oh, that.. I get it now

**Comment by Okhayeeli** [comment]
So, I tried to combine them together, but it does not seem to fit

**Comment by MayowaObisesan** [comment]
That's fine @Okhayeeli . It's fine the way it is currently as well.
Let's go with what you have. 👍

**Review by derrekcoleman — APPROVED** [review]

**Comment by derrekcoleman** [comment]
Thanks for your patience, @Okhayeeli!

@carletex or @technophile-04, please merge when you have a moment.

**Pull request merged**
