### PR TITLE
Add personal page

### PR DESCRIPTION
**Pull request by MayowaObisesan**
## Description

_Concise description of proposed changes, We recommend using screenshots and videos for better description_

## Additional Information

- [x] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [x] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

Your ENS/address: 0x09D577A4BC5422bf724ADe3735E22d7C6c8B7698

### CODE REVIEW

**Review by technophile-04 — CHANGES_REQUESTED** [review]
Thanks @MayowaObisesan, looks great !! 

I get this in console error in browser as well in terminal : 

Screenshot 2024-06-06 at 5 36 54 PM


In react we shouldn't use kebab-case and use camelCase instead, could you please update it ? 

This also happens with other things like storke-linecap etc, check browser console for all the errors, could you please fix them all ?

**Comment by derrekcoleman** [comment]
Hey @MayowaObisesan! In addition to Shiv's feedback, I just wanted to say that I appreciate how you factored out `appsList` as an array you map over. DRY 👍 

Let us know when you refactor the casing and we'll get you added 💪

**Comment by MayowaObisesan** [comment]
Oh shoot. How did I miss this?
Fixing this now. Raising an update PR.

**Comment by MayowaObisesan** [comment]
Thank you @derrekcoleman . I have raised a PR to refactor the code.

**Review by technophile-04 — APPROVED** [review]
Thanks @MayowaObisesan !! Looks great !

**Pull request merged**
